site_name: Jiber
theme: readthedocs
pages:
  - Home: 'index.md'
  - Jiber Client:
    - Client: 'jiber-client/client.md'
    - Room: 'jiber-client/room.md'
    - Settings: 'jiber-client/settings.md'
    - Store: 'jiber-client/store.md'
  - Jiber Server:
    - DB: 'jiber-server/db.md'
    - Server: 'jiber-server/server.md'
    - Settings: 'jiber-server/settings.md'
    - Store: 'jiber-server/store.md'
